---

rename_interfaces: []

wan_interface: eth0
lan_interfaces: [eth1, eth2]

ppp_provider: test
ppp_username: abcd
ppp_password: password

lan_primary_address: "{{ internal_network | ipaddr('1') }}"
lan_secondary_addresses: []
