---

- hosts: all
  gather_facts: true

- hosts: router
  roles:
    - role: networkd
      tags: [network]
    - role: ppp
      tags: [ppp, network]
    - role: dnsmasq
      tags: [dnsmasq, dns]

- hosts: router
  roles:
    - role: shorewall
      tags: [shorewall, firewall]
    - role: fail2ban
      banaction: shorewall
      tags: [fail2ban, firewall]
    - role: yay
      tags: [yay, aur]
