---

- hosts: all
  gather_facts: true

- hosts: router
  roles:
    - role: networkd
      tags: [network]
    - role: ppp
      tags: [network, wan]
    - role: dnsmasq
      tags: [dns]

- hosts: router
  roles:
    - role: shorewall
      tags: [shorewall, firewall]
    - role: fail2ban
      banaction: shorewall
      tags: [fail2ban, firewall]
