---

- name: ensure ppp is installed
  package:
    name: ppp
    state: installed
  become: true
  tags: [ppp]

- name: create udev rules
  template:
    src: udev/rules.d/network.rules.j2
    dest: /etc/udev/rules.d/10-network.rules
  become: true
  notify:
    - reboot
    - wait
  when: rename_interfaces | length > 0

- meta: flush_handlers

- name: create wan profile
  template:
    src: netctl/wan.j2
    dest: /etc/netctl/wan
  become: true
  tags: [ppp]

- name: enable wan profile
  command: netctl reenable wan
  become: true
  tags: [ppp]

- name: remove vagrant route
  command: ip route del default via 10.0.2.2
  become: true
  ignore_errors: true
  when:
    - is_vagrant is defined
    - is_vagrant | bool

- name: start wan profile
  command: netctl restart wan
  become: true
  tags: [ppp]

- name: create lan profile
  template:
    src: netctl/lan.j2
    dest: /etc/netctl/lan
  become: true

- name: enable lan profile
  command: netctl reenable lan
  become: true

- name: start lan profile
  command: netctl restart lan
  become: true

- meta: flush_handlers
