---

rename_interfaces:
  - name: wan0
    macaddress: "00:0d:b9:4b:f8:48"
  - name: lan0
    macaddress: "00:0d:b9:4b:f8:49"
  - name: lan1
    macaddress: "00:0d:b9:4b:f8:4a"


wan_interface: wan0

bridge_interface: br0
bridge_default_pvid: 2
bridge_slaves: [lan0, lan1]

# vlans:
#   - id: 2
#     name: guest
#     addresses: ["10.2.0.1/24"]
#   - id: 10
#     name: main
#     addresses: ["10.10.0.1/24"]
#   - id: 90
#     name: mgmt
#     addresses: ["10.90.0.1/24"]

# networks:
#   guest:
#     vlan_id: 2
#     subnet: 10.2.0.0/24
#   main:
#     vlan_id: 10
#     subnet: 10.10.0.0/24
#   mgmt:
#     vlan_id: 90
#     subnet: 10.90.0.0/24
