---

- name: enable dnsmasq
  service:
    name: dnsmasq
    enabled: true
    state: restarted
  become: true

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  become: true
