---

- name: enable dnscrypt-proxy
  service:
    name: dnscrypt-proxy.socket
    enabled: true
  become: true

- name: daemon-reload
  systemd:
    daemon_reload: true
  become: true

- name: start dnscrypt-proxy
  service:
    name: dnscrypt-proxy.socket
    state: started
  become: true

- name: restart dnscrypt-proxy
  service:
    name: dnscrypt-proxy.socket
    state: restarted
  become: true
