---

- name: instal dnsmasq
  package:
    name: dnsmasq
    state: present
  notify:
    - enable dnsmasq
  become: true

- name: ensure /etc/dnsmasq.d is present
  file:
    path: /etc/dnsmasq.d
    state: directory
  become: true

- name: load all files fron /etc/dnsmasq.d
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "conf-dir=/etc/dnsmasq.d/,*.conf"
  notify:
    - restart dnsmasq
  become: true

- name: configure dnsmasq
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/dnsmasq.d/{{ item }}.conf"
  become: true
  loop:
    - dhcp
    - dns
  notify:
    - restart dnsmasq

- meta: flush_handlers

- name: disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
  become: true

- name: udapte resolv.conf
  command: resolvconf -u
  become: true
