---

rename_interfaces:
  - name: wan0
    macaddress: "00:0d:b9:4b:f8:48"
  - name: lan0
    macaddress: "00:0d:b9:4b:f8:49"
  - name: lan1
    macaddress: "00:0d:b9:4b:f8:4a"

wan_interface: wan0

net_interface: ppp0
internal_network: 10.1.0.0/24

dhcp_hosts:
  - hostname: nas
    ipv4: "{{ internal_network | ipaddr('10') | ipaddr('address') }}"
    hwaddr: '32:88:5a:37:d9:a8'

domain_name: home.kidibox.net
domain_search:
  - home.kidibox.net

networks:
  guest:
    vlan_id: 2
    subnet: 10.2.0.0/24
  lan:
    vlan_id: 10
    subnet: 10.10.0.0/24
  mgmt:
    vlan_id: 90
    subnet: 10.90.0.0/24

upstream_servers:
  - "1.1.1.1"
