---

rename_interfaces:
  - name: wan0
    macaddress: "00:0d:b9:4b:f8:48"
  - name: lan0
    macaddress: "00:0d:b9:4b:f8:49"
  - name: lan1
    macaddress: "00:0d:b9:4b:f8:4a"

wan_interface: wan0
net_interface: ppp0

net_bandwidth_down: 77
net_bandwidth_up: 20

default_domain: home
external_domain: home.kidibox.net

networks:
  guest:
    vlan_id: 2
    subnet: 10.2.0.0/24
  lan:
    vlan_id: 10
    subnet: 10.10.0.0/24
  svc:
    vlan_id: 20
    subnet: 10.20.0.0/24
  lab:
    vlan_id: 50
    subnet: 10.50.0.0/24
  mgmt:
    vlan_id: 90
    subnet: 10.90.0.0/24

upstream_servers:
  - "1.1.1.1"
