---

rename_interfaces:
  - name: wan0
    macaddress: "00:0d:b9:4b:f8:48"
  - name: lan0
    macaddress: "00:0d:b9:4b:f8:49"
  - name: lan1
    macaddress: "00:0d:b9:4b:f8:4a"

wan_interface: wan0
lan_interfaces: [lan0, lan1]

dnsmasq_listen_interface: br0

net_interface: ppp0
loc_interfaces: [br0]
internal_network: 192.168.0.0/24
